### ISSUE TITLE
上传宠物页面，增加选择问卷功能

### ISSUE THREAD

**Issue by spicis** [spicis/zmengstar#11]
1.选择问卷编号，保存到宠物信息表中；
2.代码规范修订：运算符前后加空格,关键字、{}前加空格，如下
Date date = new Date();
for (int i = 0, i < 10; i++) {
    //TODO
}
3.去除前端页面中所以console.log()的代码和后端所有System.out.println()的代码

**Comment by spicis** [comment]
用户管理宠物信息的页面，图片和文字排版有点问题，要调整一下

**Comment by spicis** [comment]
3.6上传成功界面需要修改 增加分享海报功能（紧急）
  3.7上传完毕后生成宠物唯一编号（紧急）

**Comment by YangZhiChao-Java** [comment]
解决
